version: '3.3'

# elasticsearch:7.7.1的docker-compose的永世难忘的坑，environment的每个变量前加横线 - ，这个 - ES_JAVA_OPTS="-Xms256m -Xmx512m" 导致服务启不启来， 但是 docker run却没事，docker run -itd -e ES_JAVA_OPTS="-Xms256m -Xmx512m"  elasticsearch:7.7.1
# 拼音分词插件，在 https://github.com/medcl/elasticsearch-analysis-pinyin/releases 下载拼音分词插件
# 中文分词插件，在 https://github.com/medcl/elasticsearch-analysis-ik/releases 下载中文分词插件
# ansj分词插件，在 https://github.com/NLPchina/elasticsearch-analysis-ansj/releases 下载ansj分词插件
# sql插件，在 https://github.com/NLPchina/elasticsearch-sql 下载sql插件

# 在挂载的目录 plugins 创建 ik 文件夹，然后在 ik 目录里面用 unzip elasticsearch-analysis-ik-7.7.1.zip 命令解压中文分词的zip包，然后删除 这个zip包
# 在挂载的目录 plugins 创建 pinyin 文件夹，然后在 pinyin 目录里面用 unzip elasticsearch-analysis-pinyin-7.7.1.zip 命令解压拼音分词的zip包，然后删除 这个zip包
# 在挂载的目录 plugins 创建 ansj 文件夹，然后在 ansj 目录里面用 elasticsearch-analysis-ansj-7.7.1.0-release.zip 命令解压ansj分词的zip包，然后删除 这个zip包
# 在挂载的目录 plugins 创建 sql 文件夹，然后在 sql 目录里面用 unzip elasticsearch-sql-7.7.1.0.zip 命令解压sql插件的zip包，然后删除 这个zip包

# ik_max_word 分析的比较全面精准
# ik_smart 分析比较简单拆词

services:
  elasticsearch:
    image: elasticsearch:7.7.1
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - TZ=Asia/Shanghai
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
      - discovery.type=single-node
#      environment的每个变量前加横线 - ，这个 - ES_JAVA_OPTS="-Xms256m -Xmx512m" 导致服务启不启来， 但是 docker run却没事，docker run -itd --restart always -p 9200:9200 -p 9300:9300 -e ES_JAVA_OPTS="-Xms256m -Xmx512m" -e "discovery.type=single-node" --name elasticsearch elasticsearch:7.7.1
#     - ES_JAVA_OPTS="-Xms256m -Xmx256"    # 教训，这样子写，启动直接抛错
#     - ES_JAVA_OPTS=-Xms256m -Xmx256m     # 正确，这样子写，启动不抛错
#     - "ES_JAVA_OPTS=-Xms256m -Xmx512m"   # 正确，这样子写，启动不抛错
      - ES_JAVA_OPTS=-Xms512m -Xmx768m
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../plugins/es/:/usr/share/elasticsearch/plugins/
#     - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#     - ./data/esdata:/usr/share/elasticsearch/data

  logstash:
    image: logstash:7.7.1
    restart: always
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      - TZ=Asia/Shanghai
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
      - http.host=0.0.0.0
      - xpack.monitoring.enabled=true
      - xpack.monitoring.elasticsearch.username=elastic
      - xpack.monitoring.elasticsearch.password=changeme
      - xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200
    volumes:
      - /etc/localtime:/etc/localtime:ro
#     - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    links:
      - elasticsearch:elasticsearch

  kibana:
    image: kibana:7.7.1
    restart: always
    ports:
      - "5601:5601"
    environment:
      - TZ=Asia/Shanghai
      - server.name=kibana
      - server.host=0.0.0.0
      - i18n.locale=zh-CN
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    volumes:
      - /etc/localtime:/etc/localtime:ro
#     - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    links:
      - elasticsearch:elasticsearch
# 官方的 kibana:7.7.1 镜像的环境变量 elasticsearch.password and elasticsearch.username that should be ELASTICSEARCH_PASSWORD and ELASTICSEARCH_USERNAME instead

